agent {
  data_dir           = "/run/spire/data"
  log_level          = "INFO"
  server_address     = "spire-server"
  server_port        = "8443"
  socket_path        = "/run/spire/sockets/agent.sock"
  trust_domain       = "kindred.systems"
  trust_bundle_path  = "/run/spire/bootstrap/bundle.pem"
}

plugins {
  NodeAttestor "join_token" { plugin_data {} }
  KeyManager "disk" {
    plugin_data {
      directory = "/run/spire/data"
    }
  }
  WorkloadAttestor "unix"   { plugin_data {} }
}
