agent {
  data_dir           = "/run/spire/data"
  log_level          = "INFO"
  server_address     = "spire-server"
  server_port        = "8443"
  socket_path        = "/run/spire/sockets/agent.sock"
  trust_domain       = "kindred.systems"
  # Bootstraps via shared Unix socket volume from spire-server container
  insecure_bootstrap = true
}

plugins {
  NodeAttestor "join_token" { plugin_data {} }
  KeyManager "disk" {
    plugin_data {
      directory = "/run/spire/data"
    }
  }
  WorkloadAttestor "unix"   { plugin_data {} }
}
